title: Irobot 1.1
tagline: A brand new course on Learning Lab
description: 'A short test for Irobot 1.1 '
template:
  repo: irobot-1.1-template
  name: irobot-1.1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
