title: Irobot 1.1
tagline: A brand new course on Learning Lab
description: 'A short test for Irobot 1.1 '
template:
  repo: irobot-1.1-template
  name: irobot-1.1
  description: Irobot 1.1 beta
before:
  - type: createIssue
    title: Hello sir!
    body: new-issue.md
steps:
  - title: Create a branch for Irobot 1.1
    description: git init Irobot 1.1
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
